apiVersion: v1
kind: Service
metadata:  
  namespace: test
  name: service-clusterip
spec:
  selector:    
    app: nginx
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
