apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: test
spec:
  serviceName: mariadb
  selector:
    matchLabels:
      app: mysql 
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: vol-rwo
          mountPath: /var/lib/mysql
      volumes:
        - name: vol-rwo
          persistentVolumeClaim:
            claimName: rwo