apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: nginx-deployment
  labels:
    apps: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
          requests:
            memory: "128Mi"
            cpu: "64m"      
        volumeMounts:
        - name: vol-rox
          mountPath: /data/rox
        - name: vol-rwx
          mountPath: /data/rwx
        - name: vol-rwop
          mountPath: /data/rwop
      volumes:
        - name: vol-rox
          persistentVolumeClaim:
            claimName: rox
        - name: vol-rwx
          persistentVolumeClaim:
            claimName: rwx
        - name: vol-rwop
          persistentVolumeClaim:
            claimName: rwop