apiVersion: v1
kind: Service
metadata:  
  namespace: test
  name: service-nodeport
spec:
  selector:    
    app: nginx
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
