apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: hello
spec:
  containers:
    - name: hello-itme
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "256m"
        requests:
          memory: "64Mi"
          cpu: "128m"
