apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: test
spec:
  containers:
  - name: node-secret
    image: "sonlh1196/vti-configmaps:v1"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-yaml
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-yaml
          key: password